### ISSUE TITLE
HmIP-BSM - Changes in Power triggers keypress event

### ISSUE THREAD

**Issue by MarcoLaser** [SukramJ/hahomematic#1135]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I have a Zigbee Lamp connected to one of the switch outputs of a BSM. Pressing the button works fine and triggers the keypress event but sadly switching the light on or off and even changing brightness also triggers both keypress events.
Same issue on both BSM Switches i own.
The Problem is not new with 1.40.

### What version of HomematicIP (local) has the issue?

1.40

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

**Comment by SukramJ** [comment]
Please add your automation code.

**Comment by MarcoLaser** [comment]
```
alias: Neue Automatisierung
description: ""
use_blueprint:
  path: danielperna84/homematicip_local-actions-for-2-button.yaml
  input:
    remote: 3432ca89db6ad74e49d81c2248a33452
    action_top_short:
      - type: toggle
        device_id: 2dd0877cc1efab1674a258cc8316d53e
        entity_id: c1c84530f613df643e0260bccd129c85
        domain: light
```

But it also happens without any automations
