### ISSUE TITLE
set_device_value in automation failing since 1.66 - device_address is invalid for dictionary value @ data['device_address']

### ISSUE THREAD

**Issue by Fredyy90** [SukramJ/hahomematic#1731]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hey,

Since the recent update to v1.66 my automation using set_device_value is failing, with the error message: "device_address is invalid for dictionary value @ data['device_address']" sounds like the address of the device is no longer valid. I'm using HmIP-eTRV-B-2 devices and want to set the window open/closed flag.

I'm getting the address via `address: '{{ state_attr( climate_target, "address") }}'` and using the service in my automation like this:
```
  - data:
      device_address: '{{ address }}'
      channel: 1
      parameter: WINDOW_STATE
      value: 1
    action: homematicip_local.set_device_value

```

Here is the trace of the step in the automation, when if last failed, just replaces some characters in the device-adress with Xs for privacy reasons, as i don't know if it should be public.
```
Ausgeführt: 29. September 2024 um 17:28:09
Fehler: device_address is invalid for dictionary value @ data['device_address']
Ergebnis:
params:
  domain: homematicip_local
  service: set_device_value
  service_data:
    device_address: 00399XXXXXX61C:1
    channel: 1
    parameter: WINDOW_STATE
    value: 1
  target: {}
running_script: false
```

If i switch back to 1.65 everything works as expected

### What version of HomematicIP (local) has the issue?

1.66

### What was the last working version of HomematicIP (local)?

1.65

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

CCU3

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)
