### ISSUE TITLE
Temperature change trigger does not trigger

### ISSUE THREAD

**Issue by bblaha** [SukramJ/hahomematic#1790]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic) right now
- [X] I have read the [FAQs](https://github.com/danielperna84/custom_homematic#frequently-asked-questions) right now
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [X] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

I created an automation with a trigger for the thermostat temperature being set over 25°C.
The automation never gets triggered, no matter what I set the temperature to.

Below is the minimalized variant of my trigger:
`description: ""
mode: single
triggers:
  - type: temperature
    device_id: 3587b856dafb16fedcb4682f326a21c8
    entity_id: 92f8bfe1067c145d7c21e3901cf7a3f9
    domain: sensor
    trigger: device
    above: 25
    id: Temp Above 25
conditions: []
actions: []`

### What version of HomematicIP (local) has the issue?

1.68,0

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.77.7.20240826

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [X] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Log file extract. Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt
I cannot provide logs as there is no error, I just cannot get the trigger to actually trigger
```

**Comment by SukramJ** [comment]
Das ist hier kein HA Support Forum. 
Wenn die Temperaturanzeige über 25 C steigt dann ist das aus Integrationssicht abgeschlossen.

Bei mir funktioniert folgende Automatisierung:

```
alias: Heizung KH ausschalten
description: ""
triggers:
  - type: temperature
    device_id: 97aa53ebc8c4f12ee7e67783aa9ac67d
    entity_id: 59499ba50f9cb8a88272fd068b46b137
    domain: sensor
    trigger: device
    above: 15
conditions: []
actions:
  - type: turn_off
    device_id: a8790c195ebadbabd51bd42b656fd445
    entity_id: 35c2c2e0b324ff3581d61418a271164f
    domain: switch
mode: single
```
