### ISSUE TITLE
Invalid value 4.5 warning when setting temperature of thermostat

### ISSUE THREAD

**Issue by dagobert** [SukramJ/hahomematic#2099]
### I agree to the following

- [x] I have read the [documentation](https://github.com/sukramj/custom_homematic#custom_homematic) right now
- [x] I have read the [FAQs](https://github.com/sukramj/custom_homematic#frequently-asked-questions) right now
- [x] I am aware of the latest [release notes](https://github.com/sukramj/custom_homematic/releases)
- [x] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [x] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [x] I am running the latest version of the custom_component (and Home Assistant)

### The problem

This is probably related to the closed issue #1787.

It is not possible to use an action such as this to turn off the heating group because 5 is not considered off. The result is that the temperature is simply set to 5 and not turning it off.

```
action: climate.set_temperature
target:
  entity_id: climate.home_ug_zimmer2_heizgruppe
data:
  hvac_mode: "off"
  temperature: 5
```

This is also not working because a value of 4.5 is not allowed and causes an error:

```
action: climate.set_temperature
target:
  entity_id: climate.home_ug_zimmer2_heizgruppe
data:
  hvac_mode: "off"
  temperature: 4.5
```

or

```
action: climate.set_temperature
target:
  entity_id: climate.home_ug_zimmer2_heizgruppe
data:
  temperature: 4.5
```

```
Logger: homeassistant.components.websocket_api.http.connection
Quelle: components/websocket_api/commands.py:820
Integration: Home Assistant WebSocket API (Dokumentation, Probleme)
Erstmals aufgetreten: 13:26:05 (4 Vorkommnisse)
Zuletzt protokolliert: 13:27:42

[139651598115184] Provided temperature 4.5 is not valid. Accepted range is 5.0 to 30.5
```

I am using this on a HEATING-GROUP but is also does not work with Hmip-eTRV-2 and HmIP-WTH-2.

[HmIP-HEATING-dd.json](https://github.com/user-attachments/files/19089393/HmIP-HEATING-dd.json)
[HmIP-HEATING-pd.json](https://github.com/user-attachments/files/19089394/HmIP-HEATING-pd.json)

### What version of HomematicIP (local) has the issue?

1.81.2

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your homematic backend?

RaspberryMatic Standalone

### Which version of your homematic backend are you running?

3.79.6.20250118

### What hardware are you running for your system?

Proxmox

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/sukramj/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [x] Homematic IP
- [ ] Homematic (Bidcos-RF)
- [x] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Log file extract (very helpful). Anything in the logs that might be useful for us? The log (Setting/System/Logs -> load full log) is the best source to support trouble shooting!

```txt

```

### Additional information

I understand that there is another service that is for *hvac_mode* only. Using that is not always feasable. Also, HA allows setting temperature and hvac_mode in the set_temperature service.

It is not clear to me if there is any rule how to deal with this because setting the temperature to eg. 20 and at the same time turning hvac_mode to off might sound counter intuitive. In these cases I guess that the implemented logic would have to decide which setting superseeds the other. This might be special to homematic climate devices since for them, as far as I remember from many years ago implementing code with DanielPerna84 after implementing my own ccu mqtt wrapper, these are two different commands.
