### ISSUE TITLE
Add button to HM-Sen-DB-PCB

### ISSUE THREAD

**Issue by zngguvnf** [SukramJ/hahomematic#292]
**Is your feature request related to a problem? Please describe.**
I'm currently migration all of my HomeMatic devices from the old `pyhomematic` component to `hahomematic`, thank you so much for your work it's so smooth!

The only problem I have is with my `HM-Sen-DB-PCB`  (doorbell sensor):
But as with the old integration only the battery state is recognized.

**Describe the solution you'd like**
It would be cool if the entity could directly show when someone just rang the bell. Then I could send a message directly.

In RaspberryMatic the entity includes a button. Perhaps it can be integrated into homeassistant in the [same way](https://www.home-assistant.io/integrations/button/).

**Describe alternatives you've considered**
to send a message as soon as someone has rung the bell:

(Not sure if something similar can be done using hahomematic)

```
alias: Klingel
trigger:
  platform: event
  event_type: homematic.keypress
  event_data:
    name: QEQ0888785
    channel: 1
    param: PRESS_SHORT
action:
  - service: notify.mobile_app_iphone_von_matthias
    data_template: 
      title: "Homeassistant" 
      message: >
        Ding dong, es hat geklingelt.
      data: 
        push: 
          badge: 0
```

**Additional context**
