### ISSUE TITLE
Service "Homematic(IP) Local: Put paramset" und COMBINED_PARAMETER

### ISSUE THREAD

**Issue by SukramJ** [SukramJ/hahomematic#345]
### Discussed in https://github.com/danielperna84/hahomematic/discussions/344

<div type='discussions-op-text'>

<sup>Originally posted by **Baxxy13** March 19, 2022</sup>
Ich teste gerade ein bisschen mit den Services:
`Homematic(IP) Local: Put paramset` und `Homematic(IP) Local: Set device value`
Testobjekt ist eine HmIP-PSM deren Kanal:3 mit EINschaltdauer EINgeschalten werden soll.

A: Put paramset über ON_TIME & STATE --> funktioniert
```
service: hahm.put_paramset
data:
  device_id: fb2d72535aa2a37ebcb905ab82369954
  channel: 3
  paramset_key: VALUES
  paramset:
    ON_TIME: 55
    STATE: true
```
B: Put paramset über COMBINED_PARAMETER --> funktioniert nicht
```
service: hahm.put_paramset
data:
  device_id: fb2d72535aa2a37ebcb905ab82369954
  channel: 3
  paramset_key: VALUES
  paramset:
    COMBINED_PARAMETER: 'S=true,OT=55'
```
Fehlerprotokoll:
`2022-03-19 10:02:28 WARNING (MainThread) [hahomematic.client] put_paramset failed: ProxyException [(<Fault -5: 'Invalid parameter or value'>,)] 0001D3C99CA0D2:3, VALUES, {'COMBINED_PARAMETER': 'S=true,OT=55'}`

Mache ich hier was falsch? Irgendwie klappt das mit der Übergabe des Wertes `S=true,OT=55` nicht.

Als Ergänzung:
Mittels "Homematic(IP) Local: Set device value" funktionierts.
```
service: hahm.set_device_value
data:
  device_id: fb2d72535aa2a37ebcb905ab82369954
  channel: 3
  parameter: COMBINED_PARAMETER
  value: S=true,OT=55
```</div>
