### ISSUE TITLE
Scene snapshot doesn't work properly with HmRF thermostats

### ISSUE THREAD

**Issue by Puddingpanzer** [SukramJ/hahomematic#434]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.2.2

**Home Assistant version (if applicable):**
Home Assistant OS 2022.5.1

**CCU version:**
- RaspberryMatic CCU Add-On 
- Version: 3.63.9.20220430

**Problem-relevant configuration:**

Do you use tls? 
No
Do you use callback? 
No
Do you use username and password? 
Yes
Which interfaces do you use?
HmRF
HmIP
via HmIP-RFUSB

**Describe the bug**
When creating a snapshot of my HM-CC-RT-DN thermostats via scene.create (developer tools) and firing it back with scene.turn_on the "state" and "preset_mode" attributes are not set with the previous data. It seem to work with HmIP thermostats (e.g. HmIP-eTRV-B) but not with HmRF.

State before Snapshot (scene.create):

```yaml
state: heat

hvac_modes: auto, heat, off
min_temp: 4.5
max_temp: 30.5
target_temp_step: 0.5
preset_modes: boost, comfort, eco, none
current_temperature: 21.1
temperature: 17
preset_mode: none
interface_id: RaspberryMatic-BidCos-RF
address: MEQ0566489:4
entity_type: custom
friendly_name: Thermostat Wohnzimmer
supported_features: 17
hvac_action: idle
```

State after turning on snapshot (scene.turn_on)

```yaml
state: auto

hvac_modes: auto, heat, off
min_temp: 4.5
max_temp: 30.5
target_temp_step: 0.5
preset_modes: boost, comfort, eco, none
current_temperature: 21.1
temperature: 17
preset_mode: boost
interface_id: RaspberryMatic-BidCos-RF
address: MEQ0566489:4
entity_type: custom
friendly_name: Thermostat Wohnzimmer
supported_features: 17
hvac_action: idle
```

In my automation with window sensors this leads to the heating is boosting for 5 minutes everytime the window is closed. (window boost is not configured within raspberrymatic, I only work with HA automations)

**To Reproduce**
1. Go to "Developer Tools"
2. Under "states" note the state and attributes of an HMRF thermostat entity
3. Click on "Services"
4. Choose "scene.create"
5. Type a "Scene entity ID" of your choice and enter the devices entity name at "Snapshot entities" and apply the service
6. Choose "scene.turn_on" and your freshly created snapshot entity as target and apply the service
7. Check again under "states" the state and attributes of the HMRF thermostat entity, it should be different as before

**Screenshots (if applicable)**

**Relevant HA log entries (full log)**
```


```

**Diagnostic Information (available on every device)**
```


```

**Expected behavior**
Setting the states and attributes 1:1 like snapshotted when turning the scene back on

**Additional context**
This worked with the old/standard homematic integration via configuration.yaml
