### ISSUE TITLE
Pressing buttons of physical devices does not work (intended?)

### ISSUE THREAD

**Issue by meks007** [SukramJ/hahomematic#517]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.10.0

**Home Assistant version (if applicable):**
2022.7.0

**CCU version:**
Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): RaspberryMatic 3.63.9.20220625 (ova)
OS (Original, RaspberryMatic, debmatic/...):
Version: 3.63.9.20220625 (ova)

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? No
Do you use username and password? Yes
Which interfaces do you use? HmIP only

**Describe the bug**
Nicht 100% sicher, ob das überhaupt vorgesehen / ein Bug ist, aber das Drück von Button physischer Devices geht nicht.
Ich hätte den Dienst folgendermaßen angesteuert:

```
service: homematicip_local.set_device_value
data:
  device_id: 53249969bf92e9c8d81a6c163ee7b5c2
  channel: 3
  parameter: PRESS_SHORT
  value: 'true'
  value_type: boolean
```

Das Device ist ein _HmIPW-SMI55_.

Ausführung geht auf Grün, aber es passiert nichts.

Mit Node-RED das gleiche versucht, da kommt:
`"rpc > HmIP-RF setValue ["00205BE9A061FB:2","PRESS_SHORT",true] < Error: XML-RPC fault: Invalid parameter or value"`

Meine Vermutung ist jetzt, dass das nur mit der virtuellen Fernbedienung funktioniert, oder liege ich da falsch?
Sicherheitshalber eröffne ich mal einen Bug. Weil das eigentlich eine total nützliche Funktion ist, wenn's klappen würde.
