### ISSUE TITLE
Can't select HM-RC-Dis-H-x-EU device in blueprint

### ISSUE THREAD

**Issue by breti** [SukramJ/hahomematic#562]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english/german

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.13.0

**Home Assistant version (if applicable):**
2022.7.7

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): RaspberryMatic Add-On
- OS (Original, RaspberryMatic, debmatic ...): Home Assistant OS
- Version: 3.65.6.20220723

**Problem-relevant configuration:**

Do you use tls? n
Do you use callback? n
Do you use username and password? n
Which interfaces do you use (hmip/bidcos/wired)? BidCoS-RF

**Describe the bug**

I have added a 20-channel remote control HM-RC-Dis-H-x-EU to my installation. For this I copied the blueprint homematicip_local-actions-for-8-button.yaml and extended it to 20 buttons. If I now want to create an automation based on one of the blueprints, the HM-RC-Dis-H-x-EU device is not available in the device selection dropdown.

Am I making a mistake or is the HM-RC-Dis-H-x-EU not yet fully integrated?

**To Reproduce**

**Screenshots (if applicable)**
- CCU firewall
- integrations view
- device view
![grafik](https://user-images.githubusercontent.com/3628895/182199726-938a1139-5072-48d0-adb4-5e203223d298.png)

- enity view

**Relevant HA log entries (full log)**
```


```

**Diagnostic Information (available on every device)**
```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.7.7",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.15.55",
    "supervisor": "2022.07.0",
    "host_os": "Home Assistant OS 8.4",
    "docker_version": "20.10.14",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "dwd_weather": {
      "version": "1.2.22",
      "requirements": [
        "simple_dwd_weatherforecast==1.1.5",
        "markdownify==0.6.5"
      ]
    },
    "homematicip_local": {
      "version": "1.13.0",
      "requirements": [
        "hahomematic==2022.8.0"
      ]
    },
    "xiaomi_cloud_map_extractor": {
      "version": "v2.2.0",
      "requirements": [
        "pillow",
        "pybase64",
        "python-miio",
        "requests",
        "pycryptodome"
      ]
    },
    "scheduler": {
      "version": "v0.0.0",
      "requirements": []
    },
    "hacs": {
      "version": "1.26.2",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "onkyo": {
      "version": "2022.7.2",
      "requirements": [
        "onkyo-eiscp==1.2.7"
      ]
    },
    "frontier_silicon": {
      "version": "2022.3.3",
      "requirements": [
        "afsapi==0.2.3rc2"
      ]
    },
    "smartthinq_sensors": {
      "version": "0.23.6",
      "requirements": [
        "pycountry>=20.7.3",
        "xmltodict>=0.12.0",
        "chardet>=4.0.0"
      ]
    },
    "presence_simulation": {
      "version": "2.2",
      "requirements": []
    },
    "browser_mod": {
      "version": "1.5.3",
      "requirements": []
    },
    "fontawesome": {
      "version": "2.1.5",
      "requirements": []
    },
    "emulated_hue": {
      "version": "2022.7.2",
      "requirements": [
        "aiohttp_cors==0.7.0"
      ]
    },
    "mass": {
      "version": "2022.7.4",
      "requirements": [
        "music-assistant==1.7.6"
      ]
    },
    "simpleicons": {
      "version": "v2.0.0",
      "requirements": [
        "simpleicons==6.16.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "homematicip_local",
    "name": "Homematic(IP) Local",
    "config_flow": true,
    "documentation": "https://github.com/danielperna84/custom_homematic",
    "issue_tracker": "https://github.com/danielperna84/hahomematic/issues",
    "requirements": [
      "hahomematic==2022.8.0"
    ],
    "ssdp": [
      {
        "manufacturer": "EQ3",
        "manufacturerURL": "http://www.homematic.com"
      }
    ],
    "zeroconf": [],
    "homekit": {},
    "dependencies": [],
    "codeowners": [
      "@danielperna84",
      "@SukramJ"
    ],
    "iot_class": "local_push",
    "loggers": [
      "hahomematic"
    ],
    "version": "1.13.0",
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "35822aacb390d7028935d6c727a3c230",
      "version": 1,
      "domain": "homematicip_local",
      "title": "ccu",
      "data": {
        "instance_name": "ccu",
        "host": "de838cd8-raspberrymatic",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "tls": false,
        "verify_tls": false,
        "callback_host": null,
        "callback_port": null,
        "json_port": null,
        "interface": {
          "BidCos-RF": {
            "port": 2001
          },
          "HmIP-RF": {
            "port": 2010
          }
        }
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "172.30.33.3",
      "disabled_by": null
    },
    "platform_stats": {
      "binary_sensor": 58,
      "climate": 6,
      "light": 4,
      "sensor": 27,
      "switch": 14
    },
    "devices": [
      "HM-CC-TC",
      "HM-CC-VD",
      "HM-LC-Dim1PWM-CV",
      "HM-LC-Dim1T-FM",
      "HM-LC-Sw1-FM",
      "HM-LC-Sw1-Pl",
      "HM-LC-Sw2-FM",
      "HM-PB-4-WM",
      "HM-PB-6-WM55",
      "HM-PBI-4-FM",
      "HM-RC-12",
      "HM-RC-Dis-H-x-EU",
      "HM-SCI-3-FM",
      "HM-Sec-RHS",
      "HM-Sec-SCo",
      "HM-Sec-SD-2",
      "HM-Sec-SD-2-Team",
      "HM-Sen-MDIR-SM",
      "HM-Sen-MDIR-WM55"
    ]
  }
}
```

**Expected behavior**

**Additional context**
```
blueprint:
  name: Actions for 20-Button Homematic(IP) device
  description: When a button is pressed, the defined actions will be executed. Please
    keep in mind, that long-press actions might be executed multiple times, according
    to your configured minimum duration for long press. This can be configured in
    your CCU.
  domain: automation
  input:
    remote:
      name: 20-Button Device
      description: Please select a 20-Button device of your Homematic(IP) Local integration.
      selector:
        device:
          integration: homematicip_local
    action_1_short:
      name: Action
      description: Button 1, Short Press
      default: []
      selector:
        action: {}
    action_1_long:
      name: Action
      description: Button 1, Long Press
      default: []
      selector:
        action: {}
    action_2_short:
      name: Action
      description: Button 2, Short Press
      default: []
      selector:
        action: {}
    action_2_long:
      name: Action
      description: Button 2, Long Press
      default: []
      selector:
        action: {}
    action_3_short:
      name: Action
      description: Button 3, Short Press
      default: []
      selector:
        action: {}
    action_3_long:
      name: Action
      description: Button 3, Long Press
      default: []
      selector:
        action: {}
    action_4_short:
      name: Action
      description: Button 4, Short Press
      default: []
      selector:
        action: {}
    action_4_long:
      name: Action
      description: Button 4, Long Press
      default: []
      selector:
        action: {}
    action_5_short:
      name: Action
      description: Button 5, Short Press
      default: []
      selector:
        action: {}
    action_5_long:
      name: Action
      description: Button 5, Long Press
      default: []
      selector:
        action: {}
    action_6_short:
      name: Action
      description: Button 6, Short Press
      default: []
      selector:
        action: {}
    action_6_long:
      name: Action
      description: Button 6, Long Press
      default: []
      selector:
        action: {}
    action_7_short:
      name: Action
      description: Button 7, Short Press
      default: []
      selector:
        action: {}
    action_7_long:
      name: Action
      description: Button 7, Long Press
      default: []
      selector:
        action: {}
    action_8_short:
      name: Action
      description: Button 8, Short Press
      default: []
      selector:
        action: {}
    action_8_long:
      name: Action
      description: Button 8, Long Press
      default: []
      selector:
        action: {}
    action_9_short:
      name: Action
      description: Button 9, Short Press
      default: []
      selector:
        action: {}
    action_9_long:
      name: Action
      description: Button 9, Long Press
      default: []
      selector:
        action: {}
    action_10_short:
      name: Action
      description: Button 10, Short Press
      default: []
      selector:
        action: {}
    action_10_long:
      name: Action
      description: Button 10, Long Press
      default: []
      selector:
        action: {}
    action_11_short:
      name: Action
      description: Button 11, Short Press
      default: []
      selector:
        action: {}
    action_11_long:
      name: Action
      description: Button 11, Long Press
      default: []
      selector:
        action: {}
    action_12_short:
      name: Action
      description: Button 12, Short Press
      default: []
      selector:
        action: {}
    action_12_long:
      name: Action
      description: Button 12, Long Press
      default: []
      selector:
        action: {}
    action_13_short:
      name: Action
      description: Button 13, Short Press
      default: []
      selector:
        action: {}
    action_13_long:
      name: Action
      description: Button 13, Long Press
      default: []
      selector:
        action: {}
    action_14_short:
      name: Action
      description: Button 14, Short Press
      default: []
      selector:
        action: {}
    action_14_long:
      name: Action
      description: Button 14, Long Press
      default: []
      selector:
        action: {}
    action_15_short:
      name: Action
      description: Button 15, Short Press
      default: []
      selector:
        action: {}
    action_15_long:
      name: Action
      description: Button 15, Long Press
      default: []
      selector:
        action: {}
    action_16_short:
      name: Action
      description: Button 16, Short Press
      default: []
      selector:
        action: {}
    action_16_long:
      name: Action
      description: Button 16, Long Press
      default: []
      selector:
        action: {}
    action_17_short:
      name: Action
      description: Button 17, Short Press
      default: []
      selector:
        action: {}
    action_17_long:
      name: Action
      description: Button 17, Long Press
      default: []
      selector:
        action: {}
    action_18_short:
      name: Action
      description: Button 18, Short Press
      default: []
      selector:
        action: {}
    action_18_long:
      name: Action
      description: Button 18, Long Press
      default: []
      selector:
        action: {}
    action_19_short:
      name: Action
      description: Button 19, Short Press
      default: []
      selector:
        action: {}
    action_19_long:
      name: Action
      description: Button 19, Long Press
      default: []
      selector:
        action: {}
    action_20_short:
      name: Action
      description: Button 20, Short Press
      default: []
      selector:
        action: {}
    action_20_long:
      name: Action
      description: Button 20, Long Press
      default: []
      selector:
        action: {}
trigger:
- platform: event
  event_type: homematic.keypress
  event_data:
    device_id: !input 'remote'
condition: []
action:
- choose:
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 1 }}'
    sequence: !input 'action_1_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 1 }}'
    sequence: !input 'action_1_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 2 }}'
    sequence: !input 'action_2_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 2 }}'
    sequence: !input 'action_2_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 3 }}'
    sequence: !input 'action_3_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 3 }}'
    sequence: !input 'action_3_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 4 }}'
    sequence: !input 'action_4_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 4 }}'
    sequence: !input 'action_4_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 5 }}'
    sequence: !input 'action_5_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 5 }}'
    sequence: !input 'action_5_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 6 }}'
    sequence: !input 'action_6_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 6 }}'
    sequence: !input 'action_6_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 7 }}'
    sequence: !input 'action_7_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 7 }}'
    sequence: !input 'action_7_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 8 }}'
    sequence: !input 'action_8_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 8 }}'
    sequence: !input 'action_8_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 9 }}'
    sequence: !input 'action_9_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 9 }}'
    sequence: !input 'action_9_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 10 }}'
    sequence: !input 'action_10_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 10 }}'
    sequence: !input 'action_10_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 11 }}'
    sequence: !input 'action_11_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 11 }}'
    sequence: !input 'action_11_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 12 }}'
    sequence: !input 'action_12_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 12 }}'
    sequence: !input 'action_12_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 13 }}'
    sequence: !input 'action_13_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 13 }}'
    sequence: !input 'action_13_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 14 }}'
    sequence: !input 'action_14_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 14 }}'
    sequence: !input 'action_14_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 15 }}'
    sequence: !input 'action_15_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 15 }}'
    sequence: !input 'action_15_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 16 }}'
    sequence: !input 'action_16_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 16 }}'
    sequence: !input 'action_16_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 17 }}'
    sequence: !input 'action_17_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 17 }}'
    sequence: !input 'action_17_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 18 }}'
    sequence: !input 'action_18_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 18 }}'
    sequence: !input 'action_18_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 19 }}'
    sequence: !input 'action_19_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 19 }}'
    sequence: !input 'action_19_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 20 }}'
    sequence: !input 'action_20_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 20 }}'
    sequence: !input 'action_20_long'
mode: parallel
max: 10

```
