### ISSUE TITLE
Custom Entity needed for HmIP-SWSD

### ISSUE THREAD

**Issue by RehaagJ** [SukramJ/hahomematic#579]
DONT'T DELETE THIS.

**Is your feature request related to a problem? Please describe.**
hahomematic does not have full support for Homematic IP smoke detectors (HmIP-SWSD). Its Homematic counterpart (HM-Sec-SD-2) can be configured to show as smoke (the state sensor), but the "Show as" option is not available in the home assistant configuration for HmIP-SWSD. 
Consequently, it will also not be recognized as a smoke detector when provided to Apple Home through the HomeKit integration.

**Describe the solution you'd like**
A custom entity should be added to hahomematic. Looks like pyhomematic does know about HmIP-SWSD, so I hope it should be possible to port that to hahomematic.

**Describe alternatives you've considered**
Tried to use the states as they are (for example idle_off when no smoke is detected), but I wasn't able to integrate this through HomeKit as a smoke sensor.

**Additional context**

**Comment by SukramJ** [comment]
We don't have custom entities for sensors/binary_sensors.
I don't think that a custom_entity is needed for this.

The parameter `SMOKE_DETECTOR_ALARM_STATUS` has four states 
- `IDLE_OFF`
- `PRIMARY_ALARM`
- `INTRUSION_ALARM`
- `SECONDARY_ALARM`

If you want to use it in HomeKit you should create a [template binary_sensor](https://www.home-assistant.io/integrations/template/#legacy-binary-sensor-configuration-format) that is `true` if sensor value is  `primary_alarm` (state is lower case) and give it the device_class smoke.

**Comment by SukramJ** [comment]
That should look like:

```
template:
  - binary_sensor:
    - name: "Rauchmelder FL oben Smoke Detector Alarm Status"
      unique_id: "rauchmelder_fl_oben_smoke_detector_alarm_uid"
      device_class: "smoke"
      state: >
        {{ is_state('sensor.rauchmelder_fl_oben_smoke_detector_alarm_status', 'primary_alarm') }}
```

But i didn't test it. (I don't want to wast my battery)
