### ISSUE TITLE
Window channel for window open state not working

### ISSUE THREAD

**Issue by EddyVanEm** [SukramJ/hahomematic#683]
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

ENSURE that your Backend (CCU/Homegear/...) is working as expected and connected devices are controllable.

**custom_component version (if applicable):**
1.20.1

**known last working custom_component version (if applicable):**
?

**Home Assistant version (if applicable):**
2022.10.5

**CCU version:**
- Model (CCU3, Raspi3):
- OS (piVCCU):
- Version: 3.65.8

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use (hmip/bidcos/wired)? hmip

**Describe the bug**
I want to set the window open state to force the radiator valve to close. I do this via node red. This is the json that is passed on without error.
{
    "device_id" : "climate.hmip_etrv_b_00201d898ccXXX",
    "channel" : "1",
    "parameter" : "WINDOW_STATE",
    "value" : "1"
}

Have also tried:
service: homematicip_local.set_device_value
data:
  device_id: climate.hmip_etrv_b_00201d898ccXXX
  channel: 1
  parameter: WINDOW_STATE
  value: 1

**To Reproduce**
fire the event.

**Screenshots (if applicable)**
no

**Relevant HA log entries (full log)**
no explicit entry

**Expected behavior**
Set window open state

**Comment by SukramJ** [comment]
climate.hmip_etrv_b_00201d898ccXXX is not a device id as you can see from the docs.

Better you use the UI. Afterwards you can see the device id in yaml mode.

Option is to use the homematicip_local.set_device_value_raw and use an entity_id

**Comment by EddyVanEm** [comment]
I have tried to use a blueprint:
https://community.home-assistant.io/t/homematic-reduce-room-temperature-when-a-window-or-door-is-opened/341053

I am not sure but I think there are some things wrong:

```
variables:
  blocking_entity: null
  climate_target: climate.hmip_etrv_b_00201d898ccXXX
  climate_id: '{{ state_attr( climate_target, "id") }}'
  open_delay: 1
trigger:
  - platform: state
    entity_id: binary_sensor.testkontakt_state
    to: 'on'
    for: 1
condition:
  - condition: template
    value_template: >-
      {{ (blocking_entity == none) or (states[blocking_entity].state == 'off')
      }}
action:
  - service: homematic.set_device_value
    data:
      address: '{{ climate_id }}'
      channel: 1
      param: WINDOW_STATE
      value: 1
  - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.testkontakt_state
        to: 'off'
    continue_on_timeout: false
  - service: homematic.set_device_value
    data:
      address: '{{ climate_id }}'
      channel: 1
      param: WINDOW_STATE
      value: 0
mode: restart
max_exceeded: silent
id: '1666793224526'
alias: Test
description: ''

`````
For example, the service must be _homematicip_local_ I think. The climate_id seems to be null. 
<img width="323" alt="image" src="https://user-images.githubusercontent.com/34966638/198050989-47935101-9f73-4f0d-85da-4394bc2f92a2.png">
