### ISSUE TITLE
Service "Homematic(IP) Local: Put paramset": MASTER-Paramset HM-Geräte kann mit dem Hauptkanal nicht umgehen

### ISSUE THREAD

**Issue by SukramJ** [SukramJ/hahomematic#892]
### Discussed in https://github.com/danielperna84/hahomematic/discussions/891

<div type='discussions-op-text'>

<sup>Originally posted by **Baxxy13** January 26, 2023</sup>
Vorab:
Ich weiß nicht ob das buggy ist oder ich es nur nicht richtig benutze, daher erstmal zur Diskussion.

Eigentlich wollte ich testweise den BUTTON_LOCK eines HM-Heizkörperthermostates ( HM-CC-RT-DN ) setzen.
Da das nicht klappte wollte ich dann erstmal die "Beispieldaten" nutzen um das Wochenprogramm eines HM-Wandthermostaten ( HM-TC-IT-WM-W-EU ) zu ändern. Das klappt aber auch nicht.

Der Service sieht dann (ausgefüllt durch die Beispieldaten) so aus:
(angepasst ist nur die `device_address`)

```yaml
service: homematicip_local.put_paramset
data:
  device_address: LEQ0995080
  paramset_key: MASTER
  paramset:
    WEEK_PROGRAM_POINTER: 1
```
Es tut sich nichts und es gibt auch keinerlei Fehler in den HA-Logs oder den Logs der Zentrale.

Der Service zum setzen des BUTTON_LOCK sah dann exemplarisch so aus:
```yaml
service: homematicip_local.put_paramset
data:
  device_address: QEQ1958978
  paramset_key: MASTER
  paramset:
    BUTTON_LOCK: true
```
Aber auch hier keine Reaktion oder ersichtliche Fehler.

Spekulativ würde ich sagen der "Wert" ( hier `1` bzw `true` ) wird falsch interpretiert.

Wenn ich das durch den SDV generieren lasse sieht das so aus:
`" {BUTTON_LOCK {boolean true}}"; !- DatenTyp Boolean beachten`
Es wird also explizit der Datentyp mit angegeben. 

Die Möglichkeit gibt es ja bei `homematicip_local.set_device_value` mit z.B. 

```yaml
data:
  value_type: boolean
```

Vielleicht wäre das auch für `service: homematicip_local.put_paramset` nötig.

 
</div>
