### ISSUE TITLE
switch_set_on_time seems to not  work anymore

### ISSUE THREAD

**Issue by ProfDrYoMan** [SukramJ/hahomematic#916]
**custom_component version (if applicable):**
1.28.0

**known last working custom_component version (if applicable):**
?

**Home Assistant:**
- Version: 2023.2.1
- Installation method (HAOS, supervised, core, venv, Docker):  HAOS

**CCU:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...): Prox
- OS (Original, RaspberryMatic, debmatic ...): RaspiMatic
- Version: 20230114

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? ?
Do you use username and password? yes
Which interfaces do you use (hmip/bidcos/wired)? hmip/bicos

**Describe the bug**

switch_set_on_time is failing.

script action:
```
service: homematicip_local.switch_set_on_time
data:
  on_time: "{{ on_time }}"
target:
  entity_id: "{{ entity_id }}"

```

**To Reproduce**
1. Set a on time on a switch (OC-8): 3 sec
2. Set the switch to on.
3. Wait 5 sec to see that the switch is still on and stays on. 

I have a sentinel automation which switches this off after 5 sec and sends a notification. It did work for a long time and stopped sometime 4 to 1 weeks ago.
